name: guptik_desktop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  lucide_icons: ^0.257.0
  glassmorphism: ^3.0.0
  qr_flutter: ^4.1.0
  window_manager: ^0.5.1
  device_info_plus: ^10.1.0
  file_picker: ^8.0.0
  process_run: ^0.13.0
  path_provider: ^2.1.2
  sqflite_common_ffi: ^2.3.2
  supabase_flutter: ^2.3.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_web_socket: ^1.0.4
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
