name: guptik_desktop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  google_fonts: ^6.1.0
  lucide_icons: ^0.3.0 # For clean, technical icons
  glassmorphism: ^3.0.0 # For that high-tech look
  file_picker: ^6.0.0
  qr_flutter: ^4.1.0 # For Trust Me pairing
  window_manager: ^0.3.0 # To control window size/frame
  shelf: ^1.4.0              # For the internal Dart Server
  shelf_router: ^1.1.0       # Routing for the server
  shelf_web_socket: ^1.0.0   # WebSockets for Real-time Trust Me
  web_socket_channel: ^2.4.0
  process_run: ^0.12.0       # To run Docker commands
  path_provider: ^2.0.0
  sqflite_common_ffi: ^2.3.0 # Local DB for desktop settings

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
